#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and handles SIGTERM
trap 'echo "I am invincible!!!"; sleep 0.1' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
