#!/usr/bin/env bash
# This script loops from 1 t0 10 and displays diffeent values for
#+ different iterations and "Best School as default with while loop"

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
